#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Uploading comm-central
pushd $INDEX_ROOT
tar cf comm-central-hg.tar comm-central
python $AWS_ROOT/upload.py $INDEX_ROOT/comm-central-hg.tar searchfox.repositories comm-central-hg.tar
rm comm-central-hg.tar
popd

date
