#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

while read URL
do
    date

    echo Downloading index data from $URL
    mkdir $INDEX_ROOT/analysis-tmp
    pushd $INDEX_ROOT/analysis-tmp
    wget -q $URL
    unzip target.mozsearch-index.zip
    popd

    date

    echo Combining analysis
    $MOZSEARCH_PATH/scripts/combine-analysis.py $INDEX_ROOT/analysis $INDEX_ROOT/analysis-tmp

    rm -rf $INDEX_ROOT/analysis-tmp
done < $INDEX_ROOT/analysis-urls
